CachyOS/chwd

profiles/pci/graphic_drivers/profiles.toml, profiles/pci/network_drivers/profiles.toml
Changes to PKGBUILD will be posted later on
=> Move profiles from chwd-db

profiles/pci/graphic_drivers/profiles.toml
Since Rusticl is already quite ready to be used by default.
=> profiles: Remove Clover OpenCL driver from shipment

scripts/chwd
Since we use ``-Rdd`` to avoid various removal conflicts, we must be careful about removing packages such as mesa and lib32-mesa, as they are hard dependencies for most graphics applications. Removing them will break the system. Perhaps instead of such heuristics we should just remove from the profiles, since they will be pulled in by other packages anyway.
=> scripts/chwd: Prevent removal of base mesa packages

profiles/pci/graphic_drivers/profiles.toml
Causes video playback to crash constantly on X11:
```
av:h264:df0[86447]: segfault at d8 ip 00007c51716e8ab4 sp 00007c50dd5f4d18 error 4 in libX11.so.6.4.0[7c51716d9000+8b000] likely on CPU 10 (>
```
Btw, should we really install all these VDPAU drivers if VAAPI is now used everywhere and has practically replaced VDPAU?
=> profiles/nouveau: Drop libva-vdpau-driver

profiles/pci/graphic_drivers/profiles.toml
Workaround to fix broken RTD3 on GNOME, which keeps taking up 1MB of VRAM  without letting the dGPU fully sleep or keeping it running for long periods of time. 
See: https://gitlab.gnome.org/GNOME/mutter/-/issues/2969
=> Add a workaround to fix RTD3 issue on GNOME+PRIME

profiles/pci/graphic_drivers/profiles.toml
Rusticl seems to break on  Hybrid Laptops CUDA and with it Davinci Resolve and several other applications.
These tools seems to prefer it over cuda and somehow even disables cuda then.
I also remove rocm-opencl-runtime to be safe. We can handle further automatic rocm installation via AI_SDK.
=> Replace rusticl with closver-mesa

profiles/pci/graphic_drivers/profiles.toml
See: https://github.com/CachyOS/chwd/pull/118#issuecomment-2195634321
=> profiles/graphic_drivers: Add rusticl drivers as conditional_packages

profiles/pci/graphic_drivers/profiles.toml
This adds the required configuration for the libva-nvidia-driver.
This makes the VAAPI support working with the direct backend.
=> nvidia-dkms: Add LIBVA_DRIVER_NAME to profile.d

profiles/pci/graphic_drivers/profiles.toml
An user has reported to us an issue, that going into the wayland KDE session results into a blackscreen.
After debugging with the user, we have tried to remove the RTD3 workaround, since it would be not required for KDE and the issue was solved, KDE session worked without a problem.
The Laptop had following specs:
- AMD Ryzen 7 6800H
- NVIDIA GA106M [GeForce RTX 3060 Mobile / Max-Q]
from lenovo.
If we want to further carry this workaround, we should add a detection, if gnome is used and installed.
=> nvidia: Drop rt3d workaround, since it does break the wayland KDE

profiles/pci/graphic_drivers/profiles.toml
The current solution does not fix it for all systems. Lets add a wiki entry about it and keep it out of chwd for now.
=> nvidia: Drop RTD3 Workaround again

src/args.rs, src/main.rs
It allows us to replace install-gpu-drivers script in calamares just by running ``chwd --autoconfigure``.
=> chwd: Make argument for autoconfigure optional

profiles/pci/graphic_drivers/profiles.toml
I don't remember reason why this was done, but priority should definitely not be 0.
=> profiles/graphic_drivers: Increase nouveau profile priority

profiles/pci/handhelds/profiles.toml
Also comment out kernel parameters as these will be managed by systemd-boot-manager in the future
=> Updates to handheld profiles

profiles/pci/handhelds/profiles.toml
HHD has shown quite difficulty to work on the Ally and Ally X, when the upcoming kernel patches are used.
Generally, having it in the kernel space and using inputplumber on top should provide a better expierence for Ally and Ally X users.
Therefore drop hhd in favor of inputplumber.
The default configuration with inputplumber works OOB but can be further adjusted by the user in its config.
=> handheld: ally: Replace hhd with inputplumber

src/main.rs
The current version of the chwd script doesn't accept ``--device`` option, so this is dead code.
=> chwd: Remove dead code

profiles/pci/graphic_drivers/profiles.toml
nvidia-powerd service provides Dynamic Boost technology on laptops with Ampere GPUs and above, this partially unlocks the maximum TDP of dGPU. In my case on the 3050 Mobile, this raises the limit from 35W to 40W, while not causing much change in GPU temperature. This improves performance in Furmark by about ~10 FPS.
Without nvidia-powerd
With nvidia-powerd
Haven't observed any regressions yet, but testing is welcome.
=> profiles/graphic_drivers: Enable nvidia-powerd by default for Ampere+ dGPUs

profiles/pci/graphic_drivers/profiles.toml
Sad thing: Applications that running in GNOME or KDE do that as systemd user services, which don't inherit shell environment.
=> profiles/graphic_drivers: Add rusticl variable for user services

profiles/pci/graphic_drivers/profiles.toml, scripts/chwd
Inlining the `/bin/bash` call along with the `-c` key causes escaping issues and is just unnecessary because `popen` call already works within the system shell (`/bin/sh`, although it doesn't seem to prevent bashanisms from being called, but I did bring the hooks to a uniform POSIX-style). 
Should help fix issues that were earlier with the hook for RTD3 and make it easier to test for these kinds of bugs.
=> scripts/chwd: Fix issues with escaping when executing hooks

profiles/pci/graphic_drivers/profiles.toml, profiles/pci/handhelds/profiles.toml, tests/profiles/multiple-profile-raw-escaped-strings-test-parsed.toml, tests/profiles/multiple-profile-raw-escaped-strings-test.toml, tests/profiles/profile-raw-escaped-strings-test.toml
Mesa 25.1.0 deprecated opencl-clover in favour of rustictl. This now means that the previous opencl packages have essentially been "merged" into `opencl-mesa` package.
Find and replace all instances of opencl-rusticl-mesa to opencl-mesa
=> profiles: Replace mesa opencl packages with opencl-mesa

profiles/pci/handhelds/profiles.toml
During extensive testing with @Froggyman-kashee, it has been confirmed that powerbuttond also works for the Ally. Use that instead of steam-powerbuttond-git.
=> profiles/handheld: Use Valve's powerbuttond on the ROG Ally

profiles/pci/graphic_drivers/profiles.toml
Plasma 6.4 is out and will be in repos within ~3 days. The issue here is that support for X11 in kwin was split in a separate package, and we should make sure, that it will be installed for older NVIDIA GPUs, since Wayland session is completely unusable for them.
=> profiles/graphic_drivers: Install plasma-x11-session for 390.xx/470.xx

profiles/pci/graphic_drivers/profiles.toml
Since the closed profile has higher priority, it is installed first, but when installing an open profile for a different GPU, it causes a package conflict. So it's best to just skip installing open modules if there are already closed modules for the corresponding kernel.
Probably solves https://github.com/CachyOS/chwd/issues/158
=> profiles/graphic_drivers: Skip open module if a closed one is already installed

profiles/pci/handhelds/profiles.toml
This adds support for the Lenovo Legion Go S. This device comes with either a Phoenix APU or a Rembrandt APU. Hence, the profile name chosen is prefixed with `amd`, similar to what was done for the MSI Claw(s). Support in `inputplumber`, `steamos-manager` and `steamos-powerbuttond` is already available as this is an officialy supported device in SteamOS. The only remaining thing we need to add is the HID driver for this device, which has been added as of c4aab791b4c0e3747a62b6cf686dc5941e907938 and should arrive in 6.15.4.
=> profiles/handheld: Add support for Lenovo Legion Go S

profiles/pci/handhelds/profiles.toml
This is used for mura compensation on the OLED Deck. The package is already available in repositories and the only thing pending is the kernel patch required to properly support this, which will be coming in 6.15.4.
Link: https://github.com/CachyOS/CachyOS-PKGBUILDS/issues/694
=> profiles/handhelds: Install galileo-mura for Steam Deck OLED
